"""
ICOS Audit Engine
Two kinds of checks, on purpose:
  1. CODE-LEVEL checks — facts, not opinions (length, product name present,
     no other product mentioned). An AI shouldn't "judge" these — code should.
  2. AI-JUDGED checks — style/quality calls that need reading comprehension.

CHANGED 2026-09-05: was 6 checks, now 10 (still short of the full 13-module
spec — Duplication-vs-past-posts and Cross-Platform-Contamination need a
database lookup layer we haven't wired in yet; flagged, not faked).
Added: code-level length check (750-900 chars), Ordinary Content Test,
Curiosity & CTA (split out from genuine_value), explicit Humanisation Audit.
"""

import json
import config
from ai_client import get_client

MIN_LENGTH = 750
MAX_LENGTH = 900

AUDIT_PROMPT = """You are a strict content auditor for INAYA SOLUTIONS. Judge the LinkedIn post
below against these checks. For EACH check, answer PASS or FAIL with a one-sentence reason.

POST:
---
{content_text}
---

PRODUCT THIS POST MAY REFERENCE: {product_name}

CHECKS:
1. product_isolation — mentions ONLY "{product_name}", never any other product name
2. no_proprietary_leak — does NOT reveal a complete protocol/framework/internal mechanism
3. human_quality — reads like a real professional wrote it, not an AI template
4. genuine_value — contains one real, useful insight (not vague platitudes)
5. not_generic_ai — avoids AI clichés, buzzwords, "in today's fast-paced world" style openers
6. appropriate_cta — ends with a genuine reflective question, not "Thoughts?"/"Agree?"/"Comment below!"
7. curiosity_and_cta — the product mention feels like a natural bridge, not an abrupt ad switch
8. ordinary_content_test — could this have been generated by a generic LinkedIn AI content tool?
   PASS means NO (it feels original/specific), FAIL means it feels generic/replaceable
9. humanisation_audit — explicitly: does this feel human-written, with natural rhythm and warmth?
   (distinct from human_quality — this one is about voice/rhythm specifically, not just content)

Return ONLY valid JSON:
{{
  "product_isolation": {{"result": "PASS or FAIL", "reason": "..."}},
  "no_proprietary_leak": {{"result": "PASS or FAIL", "reason": "..."}},
  "human_quality": {{"result": "PASS or FAIL", "reason": "..."}},
  "genuine_value": {{"result": "PASS or FAIL", "reason": "..."}},
  "not_generic_ai": {{"result": "PASS or FAIL", "reason": "..."}},
  "appropriate_cta": {{"result": "PASS or FAIL", "reason": "..."}},
  "curiosity_and_cta": {{"result": "PASS or FAIL", "reason": "..."}},
  "ordinary_content_test": {{"result": "PASS or FAIL", "reason": "..."}},
  "humanisation_audit": {{"result": "PASS or FAIL", "reason": "..."}}
}}
No other text before or after the JSON.
"""


def _length_check(content_text: str) -> dict:
    n = len(content_text)
    if MIN_LENGTH <= n <= MAX_LENGTH:
        return {"result": "PASS", "reason": f"{n} characters, within {MIN_LENGTH}-{MAX_LENGTH} range."}
    return {"result": "FAIL", "reason": f"{n} characters — outside the required {MIN_LENGTH}-{MAX_LENGTH} range."}


def run_audit(content_text: str, product_name: str) -> tuple:
    """Returns (overall_status, results_dict). overall_status is 'PASS' or 'FAIL'."""
    results = {"length_check": _length_check(content_text)}

    response = get_client().messages.create(
        model=config.AI_MODEL,
        max_tokens=1200,
        messages=[{"role": "user", "content": AUDIT_PROMPT.format(
            content_text=content_text, product_name=product_name
        )}]
    )
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = "\n".join(l for l in raw.split("\n") if not l.strip().startswith("```"))

    try:
        ai_results = json.loads(raw)
        results.update(ai_results)
    except json.JSONDecodeError:
        results["audit_parse_error"] = {"result": "FAIL", "reason": "Could not parse audit response."}

    overall = "PASS" if all(v.get("result") == "PASS" for v in results.values()) else "FAIL"
    return overall, results
